python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Aesthetics
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Batteries
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Boards
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Capacitors
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Clocks
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Coils
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Connectors
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-DiscreteSemi
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Displays
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Electromechanical
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Fuses
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-GPS
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Hardware
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Amplifiers
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Comms
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Conversion
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Logic
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Memory
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Microcontroller
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Power
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-IC-Special-Function
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Jumpers
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-LED
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-PowerSymbols
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Resistors
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-RF
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Sensors
python ConvertSFELibs.py C:\github\SparkFun-Eagle-Libraries C:\github\SparkFun-KiCad-Libraries SparkFun-Switches
