python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-L
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-L_COPPER
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-M
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-M_COPPER
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-MINI
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-S
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty OSHW-LOGO-S_COPPER
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.3
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.4
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.05
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.5
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.6
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.7
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.8
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_.9
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_.3
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_EXPOSED_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_EXPOSED_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_COPPER_EXPOSED_.3
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_FLAME_STOP_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.3
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.4
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.5
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.6
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.7
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.8
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_.9
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_FLAME_1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.3
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.4
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.5
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.6
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.7
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.8
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_.9
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_1
rem python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LOGO_NAME_WEB
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SPARKPUNK_LOGO_.1
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SPARKPUNK_LOGO_.2
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SPECTACLE_LOGO_NEGATIVE_1.5X0.5
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SPECTACLE_LOGO_NEGATIVE_2.2X1.0
python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SPECTACLE_LOGO_TITLE_0.35X0.70
rem The ludas logo was made incorrectly, do not render
rem python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LUDUS-L
rem python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LUDUS-M
rem python ConvertModLineMultiPoly.py C:\github\SparkFun-KiCad-Libraries\Footprints\SparkFun.pretty C:\github\SparkFun-KiCad-Libraries\Tools\SparkFun-Eagle-Libraries_Conversion\Export.pretty SFE_LUDUS-S
